# @package _global_
defaults:
  - /task/leap_inhand_ball_0730/mujoco
  - _self_

training:
  replay_queue_size: 8

interactive:
  action_mode: policy
  policy_obs_mode: actor

algo:
  algo_log_name: hora_appo
  runtime_impl: hora_appo
  runtime_resolver: unilab.algos.torch.hora.appo:resolve_hora_appo_runtime
  obs_groups:
    actor:
      actor: 0
      priv_info: 0
    critic:
      actor: 0
      priv_info: 0
  actor:
    class_name: unilab.algos.torch.hora:HoraActorModel
    hidden_dims: [512, 256, 128]
    activation: elu
    obs_normalization: true
    priv_info_embed_dim: 9
    priv_mlp_hidden_dims: [256, 128, 9]
  critic:
    class_name: unilab.algos.torch.hora:HoraCriticModel
    hidden_dims: [512, 256, 128]
    activation: elu
    obs_normalization: true
    priv_info_embed_dim: 9
    priv_mlp_hidden_dims: [256, 128, 9]
  algorithm:
    learning_rate: 0.001
    desired_kl: 0.04
    adaptive_kl_factor: 1.2
    adaptive_lr_factor: 1.1

env:
  use_default_object_pose_for_object_pos_anchor: true
  obs:
    observation_mode: separated
